name: CI

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y lcov
      - name: Configure CMake
        run: |
          cmake -H. -Bbuild -DBUILD_TESTS=ON DCMAKE_CXX_FLAGS='--coverage'
      - name: Build project
        run: |
          cmake --build build --target=packageBin
      - name: Run tests
        run: |
          build/test_s
      - name: ls
        run: |
          ls
          echo " "
          ls build
      - name: Upload assets to GitHub release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/*.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
