name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y lcov
      - name: Configure CMake
        run: |
          cmake -H. -Bbuild -DBUILD_TESTS=ON DCMAKE_CXX_FLAGS='--coverage'
      - name: Build project
        run: |
          cmake --build build
      - name: Run tests
        run: |
          build/test_s
      - name: Generate coverage report
        run: |
          cd build
          lcov -c -d CMakeFiles/test_s.dir --ignore-errors mismatch --include *.cpp --output-file coverage.info
      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: build/coverage.info
